name: cronjobjob
shortDesc: "Create a job from a CronJob spec"
longDesc: ""
command: ./cronjobjob.rb
flags:
  - name: "file"
    shorthand: "f"
    desc: "Path to CronJob yaml manifest"
  - name: "dry-run"
    shorthand: "d"
    desc: "Validate manifest without publishing"
    defValue: "false"
